on:
  push:
    branches:
      - develop
name: Deploy
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.a[0].aaa += 1'  a.yml
      - run: cat a.yml

      # - run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "asset更新"
      #     git push
