on:
  push
    branches:
      - develop
name: Deploy
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.a[0].aaa += 1'  a.yml

